### PR TITLE
[19980] Initial sustainml_cpp blackbox and sustainml_modules communication test suites

### PR DESCRIPTION
**Pull request by Mario-DL**
This PR adds a first minimal test suite. 
For the `sustainml_cpp` project introduces several blackbox tests whereas for the `sustainml_modules` project it introduces the communication tests infrastructure.

This branch is currently rebased on top of `hotfix/multiple_task_processing` and **must be merged after #23**

_Note: The `sustainml_modules` project was reconverted to a cmake project_

### CODE REVIEW

**Review by JesusPoderoso — CHANGES_REQUESTED** [review]
Why is it necessary to have another "copy" of the types in the tests?
Why can't we use the already existing types from include?

**Comment by Mario-DL** [comment]
> Why is it necessary to have another "copy" of the types in the tests? Why can't we use the already existing types from include?

You are right here ! The `types` folder within `sustainml_cpp/test/blackbox`  is not necessary since it can access the `typesImpl` from `src`

**Comment by Mario-DL** [comment]
(I am manually changing the base branch since it seems that it did not change to main when we merged the previous one)

**Review by JesusPoderoso — APPROVED** [review]
LGTM with green CI

**Pull request merged**
